name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [4.2.5, 4.3.6, nightly]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - name: install dependencies for all samples
      run: |
        for i in buddy-instrument munit-mcover munit-instrument tink_unittest-instrument utest-instrument; do (
          cd ${{github.workspace}}/samples/$i; 
          npx lix download; 
          npx lix install haxe ${{matrix.haxe-version}}; 
          npx lix dev test-adapter ../../test-adapter
        ); 
        done 
      working-directory: samples/buddy # this is kind of a hack (lix bug even?)
    - name: install git version libs for Haxe nightly
      if: matrix.haxe-version == 'nightly'
      run: |
        (cd ${{github.workspace}}/samples/tink_unittest; npx lix install gh:haxetink/tink_macro)
    - name: run samples
      run: npx haxe -cp .github/workflows --run RunCICoverage
