name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [3.4.7, 4.0.5, 4.1.5, 4.2.5, nightly]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: |
        for i in buddy haxeunit hexunit munit tink_unittest utest; do (
          cd ${{github.workspace}}/samples/$i; 
          npx lix download; 
          npx lix install haxe ${{matrix.haxe-version}}; 
          npx lix dev test-adapter ../../test-adapter
        ); 
        done 
      working-directory: samples/buddy # this is kind of a hack (lix bug even?)
    - run: npx haxe -cp .github/workflows --run RunCI
