name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    strategy:
      matrix:
        haxe-version: [3.4.7, 4.0.5, 4.1.5, 4.2.5, 4.3.3, nightly]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - name: install dependencies for all samples
      run: |
        for i in buddy haxeunit hexunit munit tink_unittest utest; do (
          cd ${{github.workspace}}/samples/$i; 
          npx lix download; 
          npx lix install haxe ${{matrix.haxe-version}}; 
          npx lix dev test-adapter ../../test-adapter
        ); 
        done 
      working-directory: samples/buddy # this is kind of a hack (lix bug even?)
    - name: install older libs for Haxe 3.4.7
      if: matrix.haxe-version == '3.4.7'
      run: |
        cd ${{github.workspace}}/samples/tink_unittest
        npx lix install haxelib:tink_core#1.26.0
    - name: run samples
      run: npx haxe -cp .github/workflows --run RunCI
